[package]
name = "psl-compiled"
version = "0.1.0"
authors = ["rushmorem <rushmore@webenchanter.com>"]

[features]
dynamic = [ ]

[dependencies.psl]
version = "0.1"
path = "../psl"

[dependencies.psl-codegen]
version = "0.1"
path = "../codegen"
