[package]
name = "psl"
description = "Cache manager for the publicsuffix crate"
version = "0.0.3-pre"
license = "MIT/Apache-2.0"
repository = "https://github.com/rushmorem/psl"
documentation = "https://docs.rs/psl"
readme = "README.md"
keywords = ["tld", "gtld", "cctld", "domain", "psl"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
publicsuffix = "1.4"
lazy_static = "0.2"
parking_lot = "0.4"
slog = "2.0"
app_dirs = "1.1"

[dev-dependencies]
rspec = "1.0.0-beta.3"
slog-term = "2.0"
slog-async = "2.0"
