[workspace]
members = ["psl", "codegen", "lexer"]

[package]
name = "addr"
description = "A library for parsing domain names and email addresses"
version = "0.1.2"
license = "MIT/Apache-2.0"
repository = "https://github.com/addr-rs/addr"
documentation = "https://docs.rs/addr"
readme = "README.md"
keywords = ["tld", "gtld", "cctld", "domain", "psl"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
rental = "0.5"
error-chain = "0.12"
regex = "1.0"
lazy_static = "1.0"
idna = "0.1"

[features]
anycase = ["psl/anycase"]

[dependencies.psl]
version = "0.4"
path = "./psl"

[dev-dependencies]
rspec = "=1.0.0-beta.4"
criterion = "0.2"

[[bench]]
name = "list_benchmark"
harness = false
