[package]
name = "publicsuffix"
description = "Accurately parse domain names using The Public Suffix List"
version = "0.0.5"
license = "MIT/Apache-2.0"
repository = "https://github.com/rushmorem/publicsuffix"
documentation = "https://docs.rs/publicsuffix"
readme = "README.md"
keywords = ["tld", "gtld", "cctld", "domain", "psl"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
hyper = "0.9"
error-chain = "0.7"
idna = "0.1"
regex = "0.2"

[dev_dependencies]
rspec = "1.0.0-beta.3"
