[workspace]
members = ["psl", "codegen", "lexer"]

[package]
name = "addr"
description = "A library for parsing domain names and email addresses"
version = "0.1.1"
license = "MIT/Apache-2.0"
repository = "https://github.com/addr-rs/addr"
documentation = "https://docs.rs/addr"
readme = "README.md"
keywords = ["tld", "gtld", "cctld", "domain", "psl"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
rental = "0.5"
idna = "0.1"
error-chain = "0.12"
regex = "1.0"
lazy_static = "1.0"

[dependencies.psl]
version = "0.3"
path = "./psl"

[dev-dependencies]
rspec = "=1.0.0-beta.4"

[package.metadata.docs.rs]
rustc-args = ["--cfg",  "addr_docs_rs"]
rustdoc-args = ["--cfg",  "addr_docs_rs"]
