[package]
name = "psl"
description = "Cache manager for the publicsuffix crate"
version = "0.0.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/rushmorem/psl"
documentation = "https://docs.rs/psl"
readme = "README.md"
keywords = ["tld", "gtld", "cctld", "domain", "psl"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
publicsuffix = "1.3"
lazy_static = "0.2"
