[package]
name = "publicsuffix"
description = "Easily and accurately validate or break down any given domain name"
version = "0.0.1"
license = "MIT/Apache-2.0"
repository = "https://github.com/rushmorem/publicsuffix"
documentation = "https://docs.rs/publicsuffix"
readme = "README.md"
keywords = ["tld", "gtld", "cctld", "domain"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
reqwest = "0.2"
error-chain = "0.7"
idna = "0.1"
