[package]
name = "publicsuffix"
description = "A robust and reliable library for parsing domain names"
version = "1.3.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/rushmorem/publicsuffix"
documentation = "https://docs.rs/publicsuffix"
readme = "README.md"
keywords = ["tld", "gtld", "cctld", "domain", "psl"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

[features]
default = ["remote_list"]
remote_list = ["native-tls"]

[dependencies]
error-chain = "0.7"
idna = "0.1"
regex = "0.2"
url = "1.2"
lazy_static = "0.2"

[dependencies.native-tls]
version = "0.1"
optional = true

[dev_dependencies]
rspec = "1.0.0-beta.3"
