[package]
name = "psl-codegen"
version = "0.1.0"
authors = ["rushmorem <rushmore@webenchanter.com>"]

[lib]
proc-macro = true

[features]
default = ["prefix"]

# Whether or not to prefix the generated types
# from the `psl` crate with the name of the crate
prefix = []

[dependencies]
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.14"
sequence_trie = "0.3"
idna = "0.1"

[dependencies.psl-lexer]
version = "0.1"
path = "../lexer"
